# Generated by Django 5.1.7 on 2025-04-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='entregable',
            field=models.BooleanField(default=True),
        ),
    ]
